version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.51.0
    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Check formatting
          command: cargo fmt -- --check
      - run:
          name: Check Clippy
          command: cargo clippy -- -D warnings
      - run:
          name: Stable Build
          command: cargo build
      - run:
          name: Test
          command: cargo test
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"